### PR TITLE
Pomari Matteo

### PR DESCRIPTION
**Pull request by pomarimatteo**
Added ex 08,09,10,11

### CODE REVIEW

**Comment by zucchett** [comment]
You are modifying 04ex and 05ex, corrupting the notebooks. Please exclude the previous exercises in the PR; keep only 08ex, 09ex, 10ex, 11ex.

**Comment by pomarimatteo** [comment]
I apologize for the problems with this pull request but in an attempt to resolve conflicts I found myself forced to push other files in addition to those requested. To solve this situation should I close this pull request and create a new one or is it possible to modify this one? 
Sorry for the inconvenience

**Comment by zucchett** [comment]
No problem, you can modify this one.

**Comment by pomarimatteo** [comment]
I excluded the files from previous deliveries. It should be fine now.
Thank you.

**Pull request merged**
